[package]
name = "weather"
version = "0.1.0"
authors = ["Matthew Klein <mklein994@gmail.com>"]

[dependencies]
darksky = "0.7.0"
dotenv = "0.10.1"
futures = "0.1.17"
hyper = "0.11.9"
hyper-tls = "0.1.2"
serde = "1.0.24"
serde_derive = "1.0.24"
tokio-core = "0.1.10"
weather_icons = "0.1.0"

serde_json = "1.0.8"
