[package]
name = "weather"
version = "0.1.0"
authors = ["Matthew Klein <mklein994@gmail.com>"]

[dependencies]
clap = "~2.29.0"
darksky = { version = "0.7.0", features = ["reqwest"], default-features = false }
dotenv = "0.10.1"
env_logger = "0.4.3"
futures = "0.1.17"
hyper = "0.11.9"
hyper-tls = "0.1.2"
log = "0.4.1"
reqwest = "0.8"
serde_json = "1.0.8"
spark = { version = "0.4.0", git = "https://github.com/mklein994/rust-spark" }
streaming-stats = "0.1.28"
tokio-core = "0.1.11"
weather_icons = "0.1.0"
