[package]
name = "weather"
version = "0.1.0"
authors = ["Matthew Klein <mklein994@gmail.com>"]

[dependencies]
ansi_term = "0.10.2"
chrono = "0.4.0"
clap = "~2.29.0"
darksky = { version = "0.8.0", features = ["reqwest"], default-features = false }
dotenv = "0.10.1"
drawille = "0.2.3"
env_logger = "0.5.1"
log = "0.4.1"
reqwest = "0.8"
serde = "1.0.27"
serde_json = "1.0.8"
serde_derive = "1.0.27"
spark = { version = "0.4.0", git = "https://github.com/mklein994/rust-spark" }
toml = "0.4.5"
weather_icons = "0.2.0"
